superhero_project/superhero_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('superheros/', include('superheros.urls')),
    path('', RedirectView.as_view(url='/superheros/'))
]

superhero_project/superheros/urls.py
from django.urls import path

from . import views

app_name = 'superheros'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('<int:hero_id>/', views.detail, name = 'detail'),
    path('new/', views.create, name='create'),
    path('edit/<int:hero_id>', views.edit, name='edit'),
    path('delete/<int:hero_id>', views.delete, name='delete')
]

superhero_project/superheros/models.py
from django.db import models

# Create your models here.
class Superhero(models.Model):
    name = models.CharField(max_length=50)
    alter_ego = models.CharField(max_length=50)
    primary_ability = models.CharField(max_length=50)
    secondary_ability = models.CharField(max_length=50)
    catch_phrase = models.CharField(max_length=50)
    
    def __str__(self):
        return self.name
    

superhero_project/superheros/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .models import Superhero

# Create your views here.
def index(request):
    all_heros = Superhero.objects.all()
    context ={
        'all_heros': all_heros
    }
    return render(request, 'superheros/index.html', context)

def detail (request, hero_id):
    single_hero = Superhero.objects.get(pk=hero_id)
    context = {
        'single_hero': single_hero
    }
    return render(request, 'superheros/detail.html', context)
    
def create (request):
    if request.method == "POST":
        name = request.POST.get('name')
        alter_ego = request.POST.get('alter_ego')
        primary = request.POST.get('primary')
        secondary = request.POST.get('secondary')
        catchphrase = request.POST.get('catchphrase')
        new_hero = Superhero(name=name, alter_ego=alter_ego, primary_ability=primary, secondary_ability=secondary, catch_phrase=catchphrase)
        new_hero.save()
        return HttpResponseRedirect(reverse('superheros:index'))
        
    else:
        return render(request, 'superheros/create.html')

def edit (request, hero_id):
    hero_to_edit = Superhero.objects.get(pk=hero_id)
    context = {
        'hero': hero_to_edit
    }
    if request.method == "POST":
        hero_to_edit.name = request.POST.get('name')
        hero_to_edit.alter_ego = request.POST.get('alter_ego')
        hero_to_edit.primary_ability = request.POST.get('primary')
        hero_to_edit.secondary_ability = request.POST.get('secondary')
        hero_to_edit.catch_phrase = request.POST.get('catchphrase')
        hero_to_edit.save()
        return HttpResponseRedirect(reverse('superheros:index'))
    else:
        return render(request, 'superheros/edit.html', context) 
    
def delete(request, hero_id):
    hero_to_delete = Superhero.objects.get(pk=hero_id)
    hero_to_delete.delete()
    return HttpResponseRedirect(reverse('superheros:index'))
        
        

superhero_project/superheros/templates/superheros/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create New Hero</title>
</head>
<body>
    <h1>Create New Hero</h1>
    <form action="{% url 'superheros:create' %}" method="post">
        {% csrf_token %}
        Name: <input type="text" name="name" id="name"><br />
        Alter Ego: <input type="text" name="alter_ego" id="alter_ego"><br />
        Primary Ability: <input type="text" name="primary" id="primary"><br />
        Secondary Ability: <input type="text" name="secondary" id="secondary"><br />
        Catchphrase: <input type="text" name="catchphrase" id="catchphrase"><br />
        <input type="submit" value="Add">
    </form>
</body>
</html>

superhero_project/superheros/templates/superheros/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Details</title>
</head>
<body>
    <h1>Details</h1>
    <p>Name: {{single_hero.name}}</p>
    <p>Alter Ego: {{single_hero.alter_ego}}</p>
    <p>Primary Ability: {{single_hero.primary_ability}}</p>
    <p>Secondary Ability: {{single_hero.secondary_ability}}</p>
    <p>Catch Phrase: {{single_hero.catch_phrase}}</p>
</body>
</html>

superhero_project/superheros/templates/superheros/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit</title>
</head>
<body>
    <h1>Edit Hero</h1>
    <form action="{% url 'superheros:edit' hero.id %}" method="post">
        {% csrf_token %}
        Name: <input type="text" name="name" id="name" value={{hero.name}}><br />
        Alter Ego: <input type="text" name="alter_ego" id="alter_ego" value={{hero.alter_ego}}><br />
        Primary Ability: <input type="text" name="primary" id="primary" value={{hero.primary_ability}}><br />
        Secondary Ability: <input type="text" name="secondary" id="secondary" value={{hero.secondary_ability}}><br />
        Catchphrase: <input type="text" name="catchphrase" id="catchphrase" value={{hero.catch_phrase}}><br />
        <input type="submit" value="Edit">
    </form>
    
</body>
</html>

superhero_project/superheros/templates/superheros/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Superhero Index</title>
</head>
<body>
    <h1>List of Heroes</h1>
    <ul>
        {% for hero in all_heros %}
        <li><h2>{{hero.name}} - <a href="{% url 'superheros:detail' hero.id %}">Click for Details</a>-<a href="{% url 'superheros:edit' hero.id%}">Edit Hero</a>-<a href="{% url 'superheros:delete' hero.id %}">Delete Hero</a> <h2></li>
        {% endfor %}    
    </ul>
    <a href="{% url 'superheros:create'%}">Add New Hero</a>
    
</body>
</html>